# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The SapceBlog
email: sapcecats64@gmail.com
description: A Blog where I (spacecats64) talk about stuff that intrests me. Usually in the realm of computer science
baseurl: "" # the subpath of your site, e.g. /blog
url: "spacecats64.github.io" # the base hostname & protocol for your site
twitter_username: spacecats
github_username:  spacecats64

# Build settings
markdown: kramdown
